metadata:
  creationTimestamp: "2024-12-11T21:31:18Z"
  finalizers:
  - database.arangodb.com/graceful-shutdown
  labels:
    app: arangodb
    arango_deployment: sac
    deployment.arangodb.com/active: "true"
    deployment.arangodb.com/member: AGNT-bh7j5zwi
    deployment.arangodb.com/scheduled: "1"
    role: agent
  name: sac-agnt-bh7j5zwi-c1478a
  namespace: default
  ownerReferences:
  - apiVersion: database.arangodb.com/v1
    controller: true
    kind: ArangoDeployment
    name: sac
    uid: c22fb4b7-de56-4736-bd16-4302643e053e
  resourceVersion: "2836043"
  uid: fc40f493-227b-4e4c-8e71-c6a8a5a2cb82
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: arangodb
              arango_deployment: sac
              role: agent
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - command:
    - /usr/sbin/arangod
    - --agency.activate=true
    - --agency.disaster-recovery-id=AGNT-bh7j5zwi
    - --agency.endpoint=tcp://sac-agent-ampr1nzg.sac-int.default.svc:8529
    - --agency.endpoint=tcp://sac-agent-piomvxzf.sac-int.default.svc:8529
    - --agency.my-address=tcp://sac-agent-bh7j5zwi.sac-int.default.svc:8529
    - --agency.size=3
    - --agency.supervision=true
    - --database.directory=/data
    - --foxx.queues=false
    - --log.level=INFO
    - --log.output=+
    - --server.authentication=true
    - --server.endpoint=tcp://[::]:8529
    - --server.jwt-secret-keyfile=/secrets/cluster/jwt/token
    - --server.statistics=false
    - --server.storage-engine=rocksdb
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ARANGODB_OVERRIDE_SERVER_GROUP
      value: agent
    - name: ARANGODB_OVERRIDE_DEPLOYMENT_MODE
      value: Cluster
    - name: ARANGODB_OVERRIDE_VERSION
      value: 3.12.3
    - name: ARANGODB_OVERRIDE_ENTERPRISE
      value: "false"
    envFrom:
    - configMapRef:
        name: arangodb-operator-feature-config-map
        optional: true
    image: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /lifecycle/tools/arangodb_operator
          - lifecycle
          - preStop
          - port
    livenessProbe:
      exec:
        command:
        - /lifecycle/tools/arangodb_operator
        - lifecycle
        - probe
        - liveness
        - --auth
      failureThreshold: 10
      initialDelaySeconds: 900
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 2
    name: server
    ports:
    - containerPort: 8529
      name: server
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: arangod-data
    - mountPath: /lifecycle/tools
      name: lifecycle
    - mountPath: /secrets/cluster/jwt
      name: cluster-jwt
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-swkfx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sac-agent-bh7j5zwi
  initContainers:
  - command:
    - /usr/bin/arangodb_operator
    - lifecycle
    - copy
    - --target
    - /lifecycle/tools
    image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    imagePullPolicy: IfNotPresent
    name: init-lifecycle
    resources: {}
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /lifecycle/tools
      name: lifecycle
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-swkfx
      readOnly: true
  - command:
    - /usr/bin/arangodb_operator
    - uuid
    - --uuid-path
    - /data/UUID
    - --engine-path
    - /data/ENGINE
    - --uuid
    - AGNT-bh7j5zwi
    - --engine
    - rocksdb
    env:
    - name: MY_POD_NAMESPACE
      value: default
    image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    imagePullPolicy: IfNotPresent
    name: uuid
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: arangod-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-swkfx
      readOnly: true
  - command:
    - /usr/sbin/arangod
    - --agency.activate=true
    - --agency.disaster-recovery-id=AGNT-bh7j5zwi
    - --agency.endpoint=tcp://sac-agent-ampr1nzg.sac-int.default.svc:8529
    - --agency.endpoint=tcp://sac-agent-piomvxzf.sac-int.default.svc:8529
    - --agency.my-address=tcp://sac-agent-bh7j5zwi.sac-int.default.svc:8529
    - --agency.size=3
    - --agency.supervision=true
    - --database.directory=/data
    - --foxx.queues=false
    - --log.level=INFO
    - --log.output=+
    - --server.authentication=true
    - --server.endpoint=tcp://[::]:8529
    - --server.jwt-secret-keyfile=/secrets/cluster/jwt/token
    - --server.statistics=false
    - --server.storage-engine=rocksdb
    - --database.check-version=true
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ARANGODB_OVERRIDE_SERVER_GROUP
      value: agent
    - name: ARANGODB_OVERRIDE_DEPLOYMENT_MODE
      value: Cluster
    - name: ARANGODB_OVERRIDE_VERSION
      value: 3.12.3
    - name: ARANGODB_OVERRIDE_ENTERPRISE
      value: "false"
    envFrom:
    - configMapRef:
        name: arangodb-operator-feature-config-map
        optional: true
    image: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    imagePullPolicy: IfNotPresent
    name: version-check
    ports:
    - containerPort: 8529
      name: server
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: arangod-data
    - mountPath: /lifecycle/tools
      name: lifecycle
    - mountPath: /secrets/cluster/jwt
      name: cluster-jwt
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-swkfx
      readOnly: true
  nodeName: ip-10-0-145-209.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: sac-int
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
  volumes:
  - name: arangod-data
    persistentVolumeClaim:
      claimName: sac-agent-bh7j5zwi
  - name: cluster-jwt
    secret:
      defaultMode: 420
      secretName: sac-jwt
  - emptyDir: {}
    name: lifecycle
  - name: kube-api-access-swkfx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-12-11T21:31:31Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-12-11T21:31:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-12-11T21:31:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-12-11T21:31:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-12-11T21:31:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5e7742a9dd088cb9f8a7d53390949eeca75fed26fbf51c6707055f590f292524
    image: docker.io/arangodb/arangodb:latest
    imageID: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-12-11T21:31:35Z"
  hostIP: 10.0.145.209
  hostIPs:
  - ip: 10.0.145.209
  initContainerStatuses:
  - containerID: containerd://ca143f20eba620c1e62d81b09670fc138c2c29fa7edaf83f30417a7e6ce3b87e
    image: docker.io/arangodb/kube-arangodb:1.2.43
    imageID: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    lastState: {}
    name: init-lifecycle
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://ca143f20eba620c1e62d81b09670fc138c2c29fa7edaf83f30417a7e6ce3b87e
        exitCode: 0
        finishedAt: "2024-12-11T21:31:30Z"
        reason: Completed
        startedAt: "2024-12-11T21:31:30Z"
  - containerID: containerd://80f4027528e1458976f97d985627b7f65d91dea3fb3ec2df7ca86b0a258c2e83
    image: docker.io/arangodb/kube-arangodb:1.2.43
    imageID: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    lastState: {}
    name: uuid
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://80f4027528e1458976f97d985627b7f65d91dea3fb3ec2df7ca86b0a258c2e83
        exitCode: 0
        finishedAt: "2024-12-11T21:31:32Z"
        reason: Completed
        startedAt: "2024-12-11T21:31:31Z"
  - containerID: containerd://3bef1ac019a05fefa19d18540defe9cdd9ef3d0ef9f3df57f2c73b95376faddf
    image: docker.io/arangodb/arangodb:latest
    imageID: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    lastState: {}
    name: version-check
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://3bef1ac019a05fefa19d18540defe9cdd9ef3d0ef9f3df57f2c73b95376faddf
        exitCode: 0
        finishedAt: "2024-12-11T21:31:35Z"
        reason: Completed
        startedAt: "2024-12-11T21:31:33Z"
  phase: Running
  podIP: 10.0.144.57
  podIPs:
  - ip: 10.0.144.57
  qosClass: Burstable
  startTime: "2024-12-11T21:31:22Z"
