metadata:
  creationTimestamp: "2024-12-16T17:39:43Z"
  generation: 3
  managedFields:
  - apiVersion: database.arangodb.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"c22fb4b7-de56-4736-bd16-4302643e053e"}: {}
      f:spec:
        .: {}
        f:deploymentUID: {}
        f:group: {}
        f:id: {}
        f:template:
          .: {}
          f:checksum: {}
          f:podSpec:
            .: {}
            f:metadata:
              .: {}
              f:creationTimestamp: {}
              f:finalizers: {}
              f:labels:
                .: {}
                f:app: {}
                f:arango_deployment: {}
                f:deployment.arangodb.com/member: {}
                f:role: {}
              f:name: {}
            f:spec:
              .: {}
              f:affinity:
                .: {}
                f:nodeAffinity:
                  .: {}
                  f:requiredDuringSchedulingIgnoredDuringExecution:
                    .: {}
                    f:nodeSelectorTerms: {}
                f:podAntiAffinity:
                  .: {}
                  f:preferredDuringSchedulingIgnoredDuringExecution: {}
              f:containers: {}
              f:hostname: {}
              f:initContainers: {}
              f:restartPolicy: {}
              f:subdomain: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
              f:volumes: {}
          f:podSpecChecksum: {}
    manager: arangodb_operator
    operation: Update
    time: "2024-12-16T23:04:31Z"
  - apiVersion: database.arangodb.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:lastUpdateTime: {}
        f:message: {}
        f:template:
          .: {}
          f:checksum: {}
          f:podSpec:
            .: {}
            f:metadata:
              .: {}
              f:creationTimestamp: {}
              f:finalizers: {}
              f:labels:
                .: {}
                f:app: {}
                f:arango_deployment: {}
                f:deployment.arangodb.com/member: {}
                f:role: {}
              f:name: {}
            f:spec:
              .: {}
              f:affinity:
                .: {}
                f:nodeAffinity:
                  .: {}
                  f:requiredDuringSchedulingIgnoredDuringExecution:
                    .: {}
                    f:nodeSelectorTerms: {}
                f:podAntiAffinity:
                  .: {}
                  f:preferredDuringSchedulingIgnoredDuringExecution: {}
              f:containers: {}
              f:hostname: {}
              f:initContainers: {}
              f:restartPolicy: {}
              f:subdomain: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
              f:volumes: {}
          f:podSpecChecksum: {}
    manager: arangodb_operator
    operation: Update
    subresource: status
    time: "2024-12-18T10:31:23Z"
  name: sac-coordinator-ciuqrp5u
  namespace: default
  ownerReferences:
  - apiVersion: database.arangodb.com/v1
    controller: true
    kind: ArangoDeployment
    name: sac
    uid: c22fb4b7-de56-4736-bd16-4302643e053e
  resourceVersion: "5611261"
  uid: 64c912d6-b4f0-42a1-be46-cda9500040c1
spec:
  deploymentUID: c22fb4b7-de56-4736-bd16-4302643e053e
  group: coordinator
  id: CRDN-ciuqrp5u
  template:
    checksum: c0dfa2f17ae6e7e338dddd004b65adeaa96d10b407ceaebb5df92676bbdadd01
    podSpec:
      metadata:
        creationTimestamp: null
        finalizers:
        - pod.database.arangodb.com/delay
        - database.arangodb.com/graceful-shutdown
        labels:
          app: arangodb
          arango_deployment: sac
          deployment.arangodb.com/member: CRDN-ciuqrp5u
          role: coordinator
        name: sac-crdn-ciuqrp5u-ae16ad
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: arangodb
                    arango_deployment: sac
                    role: coordinator
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - command:
          - /usr/sbin/arangod
          - --cluster.agency-endpoint=tcp://sac-agent-ampr1nzg.sac-int.default.svc:8529
          - --cluster.agency-endpoint=tcp://sac-agent-bh7j5zwi.sac-int.default.svc:8529
          - --cluster.agency-endpoint=tcp://sac-agent-piomvxzf.sac-int.default.svc:8529
          - --cluster.my-address=tcp://sac-coordinator-ciuqrp5u.sac-int.default.svc:8529
          - --cluster.my-role=COORDINATOR
          - --database.directory=/data
          - --foxx.queues=true
          - --log.level=INFO
          - --log.output=+
          - --server.authentication=true
          - --server.endpoint=tcp://[::]:8529
          - --server.jwt-secret-keyfile=/secrets/cluster/jwt/token
          - --server.statistics=true
          - --server.storage-engine=rocksdb
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY
            value: "536870912"
          - name: ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES
            value: "1"
          - name: ARANGODB_OVERRIDE_SERVER_GROUP
            value: coordinator
          - name: ARANGODB_OVERRIDE_DEPLOYMENT_MODE
            value: Cluster
          - name: ARANGODB_OVERRIDE_VERSION
            value: 3.12.3
          - name: ARANGODB_OVERRIDE_ENTERPRISE
            value: "false"
          envFrom:
          - configMapRef:
              name: arangodb-operator-feature-config-map
              optional: true
          image: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - /lifecycle/tools/arangodb_operator
                - lifecycle
                - preStop
                - port
          name: server
          ports:
          - containerPort: 8529
            name: server
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /lifecycle/tools/arangodb_operator
              - lifecycle
              - probe
              - readiness
              - --auth
            failureThreshold: 10
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
          startupProbe:
            exec:
              command:
              - /lifecycle/tools/arangodb_operator
              - lifecycle
              - probe
              - startup
              - --auth
            failureThreshold: 720
            initialDelaySeconds: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /data
            name: arangod-data
          - mountPath: /lifecycle/tools
            name: lifecycle
          - mountPath: /secrets/cluster/jwt
            name: cluster-jwt
        hostname: sac-coordinator-ciuqrp5u
        initContainers:
        - command:
          - /usr/bin/arangodb_operator
          - lifecycle
          - copy
          - --target
          - /lifecycle/tools
          image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
          imagePullPolicy: IfNotPresent
          name: init-lifecycle
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - mountPath: /lifecycle/tools
            name: lifecycle
        - command:
          - /usr/bin/arangodb_operator
          - uuid
          - --uuid-path
          - /data/UUID
          - --engine-path
          - /data/ENGINE
          - --uuid
          - CRDN-ciuqrp5u
          - --engine
          - rocksdb
          env:
          - name: MY_POD_NAMESPACE
            value: default
          image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
          name: uuid
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - mountPath: /data
            name: arangod-data
        restartPolicy: Never
        subdomain: sac-int
        terminationGracePeriodSeconds: 3600
        tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 15
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 15
        - effect: NoExecute
          key: node.alpha.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 15
        volumes:
        - emptyDir: {}
          name: arangod-data
        - name: cluster-jwt
          secret:
            secretName: sac-jwt
        - emptyDir: {}
          name: lifecycle
    podSpecChecksum: afa614161efb62e688b00c34e91448f1ed4375f01844cd207e1a31709cd2cefa
status:
  conditions:
  - lastTransitionTime: "2024-12-16T17:39:56Z"
    lastUpdateTime: "2024-12-16T17:39:56Z"
    status: "True"
    type: MemberOfCluster
  - lastTransitionTime: "2024-12-18T10:31:00Z"
    lastUpdateTime: "2024-12-18T10:31:00Z"
    reason: ArangoDB is reachable
    status: "True"
    type: Reachable
  - lastTransitionTime: "2024-12-18T10:31:23Z"
    lastUpdateTime: "2024-12-18T10:31:23Z"
    reason: Pod Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-12-18T10:31:23Z"
    lastUpdateTime: "2024-12-18T10:31:23Z"
    reason: Pod Serving
    status: "True"
    type: Serving
  - lastTransitionTime: "2024-12-18T10:30:56Z"
    lastUpdateTime: "2024-12-18T10:30:56Z"
    message: Assigned to node ip-10-0-146-13.us-west-2.compute.internal
    reason: Pod is scheduled
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2024-12-18T10:30:59Z"
    lastUpdateTime: "2024-12-18T10:30:59Z"
    reason: Core Pod Container started
    status: "True"
    type: Active
  - lastTransitionTime: "2024-12-18T10:31:23Z"
    lastUpdateTime: "2024-12-18T10:31:23Z"
    reason: Pod Started
    status: "True"
    type: Started
  lastUpdateTime: "2024-12-18T10:31:23Z"
  message: Member is Ready
  template:
    checksum: c0dfa2f17ae6e7e338dddd004b65adeaa96d10b407ceaebb5df92676bbdadd01
    podSpec:
      metadata:
        creationTimestamp: null
        finalizers:
        - pod.database.arangodb.com/delay
        - database.arangodb.com/graceful-shutdown
        labels:
          app: arangodb
          arango_deployment: sac
          deployment.arangodb.com/member: CRDN-ciuqrp5u
          role: coordinator
        name: sac-crdn-ciuqrp5u-ae16ad
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: arangodb
                    arango_deployment: sac
                    role: coordinator
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - command:
          - /usr/sbin/arangod
          - --cluster.agency-endpoint=tcp://sac-agent-ampr1nzg.sac-int.default.svc:8529
          - --cluster.agency-endpoint=tcp://sac-agent-bh7j5zwi.sac-int.default.svc:8529
          - --cluster.agency-endpoint=tcp://sac-agent-piomvxzf.sac-int.default.svc:8529
          - --cluster.my-address=tcp://sac-coordinator-ciuqrp5u.sac-int.default.svc:8529
          - --cluster.my-role=COORDINATOR
          - --database.directory=/data
          - --foxx.queues=true
          - --log.level=INFO
          - --log.output=+
          - --server.authentication=true
          - --server.endpoint=tcp://[::]:8529
          - --server.jwt-secret-keyfile=/secrets/cluster/jwt/token
          - --server.statistics=true
          - --server.storage-engine=rocksdb
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY
            value: "536870912"
          - name: ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES
            value: "1"
          - name: ARANGODB_OVERRIDE_SERVER_GROUP
            value: coordinator
          - name: ARANGODB_OVERRIDE_DEPLOYMENT_MODE
            value: Cluster
          - name: ARANGODB_OVERRIDE_VERSION
            value: 3.12.3
          - name: ARANGODB_OVERRIDE_ENTERPRISE
            value: "false"
          envFrom:
          - configMapRef:
              name: arangodb-operator-feature-config-map
              optional: true
          image: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - /lifecycle/tools/arangodb_operator
                - lifecycle
                - preStop
                - port
          name: server
          ports:
          - containerPort: 8529
            name: server
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /lifecycle/tools/arangodb_operator
              - lifecycle
              - probe
              - readiness
              - --auth
            failureThreshold: 10
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
          startupProbe:
            exec:
              command:
              - /lifecycle/tools/arangodb_operator
              - lifecycle
              - probe
              - startup
              - --auth
            failureThreshold: 720
            initialDelaySeconds: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /data
            name: arangod-data
          - mountPath: /lifecycle/tools
            name: lifecycle
          - mountPath: /secrets/cluster/jwt
            name: cluster-jwt
        hostname: sac-coordinator-ciuqrp5u
        initContainers:
        - command:
          - /usr/bin/arangodb_operator
          - lifecycle
          - copy
          - --target
          - /lifecycle/tools
          image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
          imagePullPolicy: IfNotPresent
          name: init-lifecycle
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - mountPath: /lifecycle/tools
            name: lifecycle
        - command:
          - /usr/bin/arangodb_operator
          - uuid
          - --uuid-path
          - /data/UUID
          - --engine-path
          - /data/ENGINE
          - --uuid
          - CRDN-ciuqrp5u
          - --engine
          - rocksdb
          env:
          - name: MY_POD_NAMESPACE
            value: default
          image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
          name: uuid
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - mountPath: /data
            name: arangod-data
        restartPolicy: Never
        subdomain: sac-int
        terminationGracePeriodSeconds: 3600
        tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 15
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 15
        - effect: NoExecute
          key: node.alpha.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 15
        volumes:
        - emptyDir: {}
          name: arangod-data
        - name: cluster-jwt
          secret:
            secretName: sac-jwt
        - emptyDir: {}
          name: lifecycle
    podSpecChecksum: afa614161efb62e688b00c34e91448f1ed4375f01844cd207e1a31709cd2cefa
