apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-test-pod
  namespace: data-stack-dev
  labels:
    app: aws-cli-test
spec:
  serviceAccountName: spark-bucket-read-sa
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command: ["sleep", "3600"]  # Keep the container running for 1 hour
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
  terminationGracePeriodSeconds: 30