apiVersion: scheduler.arangodb.com/v1beta1
kind: ArangoProfile
metadata:
  creationTimestamp: "2024-12-11T21:30:59Z"
  generation: 1
  name: sac-int-authn-v1
  namespace: default
  ownerReferences:
  - apiVersion: database.arangodb.com/v1
    controller: true
    kind: ArangoDeployment
    name: sac
    uid: c22fb4b7-de56-4736-bd16-4302643e053e
  resourceVersion: "2835261"
  uid: 89081744-6d48-490f-9e83-05dba6dd13c0
spec:
  selectors:
    label:
      matchLabels:
        integration.profiles.arangodb.com/authn: v1
        profiles.arangodb.com/deployment: sac
  template:
    container:
      all: {}
      containers:
        integration:
          env:
          - name: INTEGRATION_AUTHENTICATION_V1_INTERNAL
            value: "true"
          - name: INTEGRATION_AUTHENTICATION_V1_EXTERNAL
            value: "false"
          - name: INTEGRATION_AUTHENTICATION_V1
            value: "true"
          - name: INTEGRATION_AUTHENTICATION_V1_ENABLED
            value: "true"
          - name: INTEGRATION_AUTHENTICATION_V1_PATH
            value: /secrets/cluster/jwt
          volumeMounts:
          - mountPath: /secrets/cluster/jwt
            name: cluster-jwt
            readOnly: true
    pod:
      volumes:
      - name: cluster-jwt
        secret:
          secretName: sac-jwt-folder
    priority: 127
status:
  accepted:
    checksum: 1987506e047bac11830e0d5023eccc7e8c17caa6d37e2ec7f0e82a1b88a67ca7
    template:
      container:
        all: {}
        containers:
          integration:
            env:
            - name: INTEGRATION_AUTHENTICATION_V1_INTERNAL
              value: "true"
            - name: INTEGRATION_AUTHENTICATION_V1_EXTERNAL
              value: "false"
            - name: INTEGRATION_AUTHENTICATION_V1
              value: "true"
            - name: INTEGRATION_AUTHENTICATION_V1_ENABLED
              value: "true"
            - name: INTEGRATION_AUTHENTICATION_V1_PATH
              value: /secrets/cluster/jwt
            volumeMounts:
            - mountPath: /secrets/cluster/jwt
              name: cluster-jwt
              readOnly: true
      pod:
        volumes:
        - name: cluster-jwt
          secret:
            secretName: sac-jwt-folder
      priority: 127
  conditions:
  - lastTransitionTime: "2024-12-11T21:31:00Z"
    lastUpdateTime: "2024-12-11T21:31:00Z"
    message: Spec is valid
    reason: Spec is valid
    status: "True"
    type: SpecValid
  - lastTransitionTime: "2024-12-11T21:31:02Z"
    lastUpdateTime: "2024-12-11T21:31:02Z"
    message: Ready
    reason: Ready
    status: "True"
    type: Ready
