metadata:
  creationTimestamp: "2024-12-18T11:00:35Z"
  finalizers:
  - database.arangodb.com/graceful-shutdown
  labels:
    app: arangodb
    arango_deployment: sac
    deployment.arangodb.com/active: "true"
    deployment.arangodb.com/member: PRMR-t79dxjnh
    deployment.arangodb.com/scheduled: "1"
    role: dbserver
  name: sac-prmr-t79dxjnh-7f2b55
  namespace: default
  ownerReferences:
  - apiVersion: database.arangodb.com/v1
    controller: true
    kind: ArangoDeployment
    name: sac
    uid: c22fb4b7-de56-4736-bd16-4302643e053e
  resourceVersion: "5620976"
  uid: 073b4b00-e6ab-458b-889d-e2622290b5c6
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: arangodb
              arango_deployment: sac
              role: dbserver
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - command:
    - /usr/sbin/arangod
    - --cluster.agency-endpoint=tcp://sac-agent-ampr1nzg.sac-int.default.svc:8529
    - --cluster.agency-endpoint=tcp://sac-agent-bh7j5zwi.sac-int.default.svc:8529
    - --cluster.agency-endpoint=tcp://sac-agent-piomvxzf.sac-int.default.svc:8529
    - --cluster.my-address=tcp://sac-dbserver-t79dxjnh.sac-int.default.svc:8529
    - --cluster.my-role=PRIMARY
    - --database.directory=/data
    - --foxx.queues=false
    - --log.level=INFO
    - --log.output=+
    - --server.authentication=true
    - --server.early-connections=true
    - --server.endpoint=tcp://[::]:8529
    - --server.jwt-secret-keyfile=/secrets/cluster/jwt/token
    - --server.statistics=true
    - --server.storage-engine=rocksdb
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY
      value: "2147483648"
    - name: ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES
      value: "1"
    - name: ARANGODB_OVERRIDE_SERVER_GROUP
      value: dbserver
    - name: ARANGODB_OVERRIDE_DEPLOYMENT_MODE
      value: Cluster
    - name: ARANGODB_OVERRIDE_VERSION
      value: 3.12.3
    - name: ARANGODB_OVERRIDE_ENTERPRISE
      value: "false"
    envFrom:
    - configMapRef:
        name: arangodb-operator-feature-config-map
        optional: true
    image: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /lifecycle/tools/arangodb_operator
          - lifecycle
          - preStop
          - port
    livenessProbe:
      exec:
        command:
        - /lifecycle/tools/arangodb_operator
        - lifecycle
        - probe
        - liveness
        - --auth
      failureThreshold: 2147483647
      initialDelaySeconds: 900
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 2
    name: server
    ports:
    - containerPort: 8529
      name: server
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - ALL
    startupProbe:
      exec:
        command:
        - /lifecycle/tools/arangodb_operator
        - lifecycle
        - probe
        - startup
        - --auth
      failureThreshold: 2147483647
      initialDelaySeconds: 1
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: arangod-data
    - mountPath: /lifecycle/tools
      name: lifecycle
    - mountPath: /secrets/cluster/jwt
      name: cluster-jwt
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnmdx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sac-dbserver-t79dxjnh
  initContainers:
  - command:
    - /usr/bin/arangodb_operator
    - lifecycle
    - copy
    - --target
    - /lifecycle/tools
    image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    imagePullPolicy: IfNotPresent
    name: init-lifecycle
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /lifecycle/tools
      name: lifecycle
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnmdx
      readOnly: true
  - command:
    - /usr/bin/arangodb_operator
    - uuid
    - --uuid-path
    - /data/UUID
    - --engine-path
    - /data/ENGINE
    - --uuid
    - PRMR-t79dxjnh
    - --engine
    - rocksdb
    - --require
    env:
    - name: MY_POD_NAMESPACE
      value: default
    image: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    imagePullPolicy: IfNotPresent
    name: uuid
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: arangod-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnmdx
      readOnly: true
  - command:
    - /usr/sbin/arangod
    - --cluster.agency-endpoint=tcp://sac-agent-ampr1nzg.sac-int.default.svc:8529
    - --cluster.agency-endpoint=tcp://sac-agent-bh7j5zwi.sac-int.default.svc:8529
    - --cluster.agency-endpoint=tcp://sac-agent-piomvxzf.sac-int.default.svc:8529
    - --cluster.my-address=tcp://sac-dbserver-t79dxjnh.sac-int.default.svc:8529
    - --cluster.my-role=PRIMARY
    - --database.directory=/data
    - --foxx.queues=false
    - --log.level=INFO
    - --log.output=+
    - --server.authentication=true
    - --server.early-connections=true
    - --server.endpoint=tcp://[::]:8529
    - --server.jwt-secret-keyfile=/secrets/cluster/jwt/token
    - --server.statistics=true
    - --server.storage-engine=rocksdb
    - --database.check-version=true
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY
      value: "2147483648"
    - name: ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES
      value: "1"
    - name: ARANGODB_OVERRIDE_SERVER_GROUP
      value: dbserver
    - name: ARANGODB_OVERRIDE_DEPLOYMENT_MODE
      value: Cluster
    - name: ARANGODB_OVERRIDE_VERSION
      value: 3.12.3
    - name: ARANGODB_OVERRIDE_ENTERPRISE
      value: "false"
    envFrom:
    - configMapRef:
        name: arangodb-operator-feature-config-map
        optional: true
    image: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    imagePullPolicy: IfNotPresent
    name: version-check
    ports:
    - containerPort: 8529
      name: server
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: arangod-data
    - mountPath: /lifecycle/tools
      name: lifecycle
    - mountPath: /secrets/cluster/jwt
      name: cluster-jwt
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnmdx
      readOnly: true
  nodeName: ip-10-0-114-234.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: sac-int
  terminationGracePeriodSeconds: 3600
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: arangod-data
    persistentVolumeClaim:
      claimName: sac-dbserver-t79dxjnh
  - name: cluster-jwt
    secret:
      defaultMode: 420
      secretName: sac-jwt
  - emptyDir: {}
    name: lifecycle
  - name: kube-api-access-rnmdx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-12-18T11:00:51Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-12-18T11:00:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-12-18T11:00:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-12-18T11:00:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-12-18T11:00:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://9a4dc8cfcd680c6758ddb6e8fe3a30d1e112ca5a237a04afdba970d865ba1e6d
    image: sha256:44fa47c4e0035cd86636f6fd9e67ed936015ccc13d48955694cb54d399111e25
    imageID: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-12-18T11:00:54Z"
  hostIP: 10.0.114.234
  hostIPs:
  - ip: 10.0.114.234
  initContainerStatuses:
  - containerID: containerd://a42fd62a75ea476c713046821eb5e41e2b08c1cee05004b8f7c327007effc2ef
    image: sha256:c33ee5763fe3c73319902d95bcd75814a12c5b2b4a9e726edadf0a1d2226e4f1
    imageID: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    lastState: {}
    name: init-lifecycle
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://a42fd62a75ea476c713046821eb5e41e2b08c1cee05004b8f7c327007effc2ef
        exitCode: 0
        finishedAt: "2024-12-18T11:00:51Z"
        reason: Completed
        startedAt: "2024-12-18T11:00:51Z"
  - containerID: containerd://1654d44c349f3b9f5f5075ff0866ee0ba6aa6d4cfa00fb887f0f4d0d01a200e5
    image: sha256:c33ee5763fe3c73319902d95bcd75814a12c5b2b4a9e726edadf0a1d2226e4f1
    imageID: docker.io/arangodb/kube-arangodb@sha256:91307ff853fe8259a60104aefc91e7f47ed904c333fd402d0f361d2cbca1b862
    lastState: {}
    name: uuid
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://1654d44c349f3b9f5f5075ff0866ee0ba6aa6d4cfa00fb887f0f4d0d01a200e5
        exitCode: 0
        finishedAt: "2024-12-18T11:00:51Z"
        reason: Completed
        startedAt: "2024-12-18T11:00:51Z"
  - containerID: containerd://fcacabea93ab9dd74bbf2a3dbba36e038684bf1e527a9f5a8edd2a0f18c70831
    image: sha256:44fa47c4e0035cd86636f6fd9e67ed936015ccc13d48955694cb54d399111e25
    imageID: docker.io/arangodb/arangodb@sha256:d1404a73c007853abc922d4d38bab364b69b1034f5057ef9e3e72d74e2eecbd6
    lastState: {}
    name: version-check
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://fcacabea93ab9dd74bbf2a3dbba36e038684bf1e527a9f5a8edd2a0f18c70831
        exitCode: 0
        finishedAt: "2024-12-18T11:00:54Z"
        reason: Completed
        startedAt: "2024-12-18T11:00:52Z"
  phase: Running
  podIP: 10.0.118.161
  podIPs:
  - ip: 10.0.118.161
  qosClass: Guaranteed
  startTime: "2024-12-18T11:00:35Z"
