apiVersion: v1
kind: Secret
metadata:
  name: arangodb-cluster-backup-credentials
type: Opaque
stringData:
  token: |
    {
      "s3": {
        "type": "s3",
        "provider": "AWS",
        "env_auth": "true",
        "location_constraint": "us-west-2",
        "region": "us-west-2",
        "acl": "private",
        "no_check_bucket": "true"
      }
    }
