apiVersion: v1
kind: Secret
metadata:
  name: cdk-kubernetes-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/IGVF-DACC/cdk-kubernetes.git
  type: git
  # username: <your_username>
